Debian 11 worker; Py3 only
gnuradio/gnuradio-buildbot pull request #44
Opened 2020-12-19 20:35 UTC by marcusmueller

2020-12-19 20:53 UTC, marcusmueller commented
Successfully builds current master.

2021-01-10 01:11 UTC, blaquezzz approved these changes

2021-01-10 13:01 UTC, noc0lour requested changes
Just update the maintainer name

2021-01-10 13:01 UTC, noc0lour commented on worker/debian-11.Dockerfile
> +MAINTAINER Andrej Rode <mail@andrejro.de>
Put your name here

2021-01-16 14:47 UTC, merged